# -*- coding: utf-8 -*-
"""Proyek_Analisis_Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QEp8GJeuzoU5XvKt1AuFG_ffI4eBVZX5

# Proyek Analisis Data: Air Quality Dataset
- **Nama:** Mochammad Wahyu Ramadhan
- **Email:** wahyuramadhan9090@gmail.com
- **ID Dicoding:** wahyuramadhan

## Menentukan Pertanyaan

- Bagaimana kondisi kualitas udara berdasarkan nilai konsentrasi polutan (PM2.5, PM10, NO2, CO, dll)?
- Polutan apa yang paling sering melebihi ambang batas kualitas udara?

## Import Semua Packages/Library yang Digunakan
"""

!pip install streamlit

import streamlit as st

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import os
import matplotlib.dates as mdates

"""## Data Wrangling

### Gathering Data
"""

import os

path = "data"
csv_files = [f for f in os.listdir(path) if f.endswith(".csv")]
csv_files

import os
import shutil

os.makedirs("data", exist_ok=True)

for f in os.listdir("/content"):
    if f.endswith(".csv"):
        shutil.move(f"/content/{f}", f"/content/data/{f}")

path = "data"
csv_files = [f for f in os.listdir(path) if f.endswith(".csv")]

df_list = []

for file in csv_files:
    file_path = os.path.join(path, file)
    df = pd.read_csv(file_path)
    print(df.head())
    df_list.append(df)

air_quality_df = pd.concat(df_list, ignore_index=True)

# hitung banyak file
num_files = len(csv_files)
print(f"Jumlah file CSV dalam dataset: {num_files}")
print("Nama-nama file CSV dalam dataset:")
for file in csv_files:
    print(file)

"""**Insight:**
- Data yang dianalisis merupakan data kualitas udara yang berasal dari beberapa file CSV.
- Setiap file merepresentasikan satu stasiun pemantauan kualitas udara, sehingga data yang digunakan mencerminkan kondisi kualitas udara dari berbagai lokasi pengukuran.

### Assessing Data
"""

air_quality_df.info()

cek_missing = pd.DataFrame({
    'Kolom': air_quality_df.columns,
    'Banyak Missing Value': air_quality_df.isnull().sum(),
    'Persentase Missing Value': air_quality_df.isnull().mean() * 100
})
cek_missing

print("Jumlah duplikasi: ", air_quality_df.duplicated().sum())

air_quality_df.describe(include='all')

categorical_columns = ['station', 'year', 'month', 'day', 'hour', 'wd']
for col in categorical_columns:
    unique_values = air_quality_df[col].unique()
    print(f"Kolom '{col}' memiliki {len(unique_values)} nilai unik: {unique_values}\n")

"""**Insight:**
- Berdasarkan hasil pengecekan awal, dataset memiliki kombinasi tipe data numerik dan non-numerik yang sesuai dengan kebutuhan analisis.
- Beberapa variabel, khususnya pada polutan udara dan faktor meteorologi, masih mengandung nilai kosong, dengan jumlah terbesar terdapat pada variabel CO.

### Cleaning Data
"""

numeric_columns = air_quality_df.select_dtypes(include=[np.number]).columns

agg_numeric = air_quality_df.groupby('station')[numeric_columns].mean().reset_index()
print("Rata-rata kolom numerik per stasiun:")
print(agg_numeric)

categorical_columns = air_quality_df.select_dtypes(include=['object']).columns
categorical_columns = [col for col in categorical_columns if col != 'station']

agg_categorical = air_quality_df.groupby('station')[categorical_columns].agg(lambda x: x.mode().iloc[0]).reset_index()
print("Modus kolom kategorik per stasiun:")
print(agg_categorical)

numeric_columns = air_quality_df.select_dtypes(include=[np.number]).columns
for col in numeric_columns:
    air_quality_df[col] = (
        air_quality_df
        .groupby('station')[col]
        .transform(lambda x: x.fillna(x.mean()))
    )

categorical_columns = air_quality_df.select_dtypes(include=['object']).columns
for col in categorical_columns:
    air_quality_df[col] = (
        air_quality_df
        .groupby('station')[col]
        .transform(lambda x: x.fillna(x.mode()[0]))
    )

air_quality_df.info()
air_quality_df.head()

air_quality_df['datetime'] = pd.to_datetime(
    air_quality_df[['year','month','day','hour']]
)
air_quality_df.head()

air_quality_df.to_csv("air_quality_cleaned.csv", index=False)

"""**Insight:**
- Penanganan missing value dilakukan dengan mempertimbangkan perbedaan karakteristik antar stasiun, sehingga imputasi dilakukan berdasarkan kelompok stasiun masing-masing.
- Pendekatan ini membantu menjaga representasi data numerik dan kategorik agar tidak bias terhadap stasiun lain.

## Exploratory Data Analysis (EDA)

### Explore ...
"""

air_quality_df.describe(include='all')

daily_pm25 = (
    air_quality_df
    .set_index('datetime')
    .groupby('station')['PM2.5']
    .resample('D')
    .mean()
    .reset_index()
)

daily_pm25.head()

daily_pm25.groupby('station').agg({'PM2.5': ['mean', 'min', 'max', 'std']}).reset_index()

monthly_pm25 = (
    air_quality_df
    .set_index('datetime')
    .groupby('station')['PM2.5']
    .resample('M')
    .mean()
    .reset_index()
)

monthly_pm25.head()

monthly_pm25.groupby('station').agg({'PM2.5': ['mean', 'min', 'max', 'std']}).reset_index()

annual_pm25 = (
    air_quality_df
    .set_index('datetime')
    .groupby('station')['PM2.5']
    .resample('Y')
    .mean()
    .reset_index()
)

annual_pm25.head()

annual_pm25.groupby('station').agg({'PM2.5': ['mean', 'min', 'max', 'std']}).reset_index()

"""**Insight:**
- Data kualitas udara yang digunakan memiliki cakupan observasi yang besar dengan resolusi waktu per jam, sehingga memungkinkan analisis tren jangka panjang.
- Variabel arah angin juga menunjukkan pola tertentu, dengan beberapa kategori arah lebih sering muncul dan berpotensi memengaruhi distribusi polutan.

## Visualization & Explanatory Analysis

### Pertanyaan 1: agaimana dinamika konsentrasi PM2.5 dalam rentang waktu 2013 hingga 2017?
"""

plt.figure(figsize=(14, 6))

sns.lineplot(
    data=daily_pm25,
    x="datetime",
    y="PM2.5",
    hue="station"
)

plt.title("Perubahan Konsentrasi PM2.5 Harian (2013–2017) di Berbagai Stasiun")
plt.xlabel("Periode Waktu")
plt.ylabel("Rata-rata PM2.5 (µg/m³)")

axis = plt.gca()
axis.xaxis.set_major_locator(mdates.MonthLocator(interval=2))
axis.xaxis.set_major_formatter(mdates.DateFormatter("%b %Y"))
plt.xticks(rotation=45)

pm25_max = daily_pm25["PM2.5"].max()
pm25_min = daily_pm25["PM2.5"].min()

plt.axhline(pm25_max, linestyle="--", linewidth=1, label=f"Nilai Maksimum: {pm25_max:.2f}")
plt.axhline(pm25_min, linestyle="--", linewidth=1, label=f"Nilai Minimum: {pm25_min:.2f}")

row_max = daily_pm25.loc[daily_pm25["PM2.5"].idxmax()]
row_min = daily_pm25.loc[daily_pm25["PM2.5"].idxmin()]

plt.annotate(
    f"Maks ({row_max['station']}, {row_max['datetime'].strftime('%b %Y')})",
    xy=(row_max["datetime"], pm25_max),
    xytext=(0, 10),
    textcoords="offset points",
    ha="center"
)

plt.annotate(
    f"Min ({row_min['station']}, {row_min['datetime'].strftime('%b %Y')})",
    xy=(row_min["datetime"], pm25_min),
    xytext=(0, -15),
    textcoords="offset points",
    ha="center"
)

plt.legend(title="Stasiun Pemantauan", bbox_to_anchor=(1.05, 1), loc="upper left")
plt.tight_layout()
plt.show()

plt.figure(figsize=(14, 6))

sns.lineplot(
    data=monthly_pm25,
    x="datetime",
    y="PM2.5",
    hue="station"
)

plt.title("Pola Bulanan Konsentrasi PM2.5 Periode 2013–2017")
plt.xlabel("Periode Waktu")
plt.ylabel("Rata-rata PM2.5 (µg/m³)")

axis = plt.gca()
axis.xaxis.set_major_locator(mdates.MonthLocator(interval=3))
axis.xaxis.set_major_formatter(mdates.DateFormatter("%b %Y"))
plt.xticks(rotation=45)

pm25_max = monthly_pm25["PM2.5"].max()
pm25_min = monthly_pm25["PM2.5"].min()

plt.axhline(pm25_max, linestyle="--", linewidth=1, label=f"Nilai Tertinggi: {pm25_max:.2f}")
plt.axhline(pm25_min, linestyle="--", linewidth=1, label=f"Nilai Terendah: {pm25_min:.2f}")

row_max = monthly_pm25.loc[monthly_pm25["PM2.5"].idxmax()]
row_min = monthly_pm25.loc[monthly_pm25["PM2.5"].idxmin()]

plt.annotate(
    f"Tertinggi ({row_max['station']} – {row_max['datetime'].strftime('%b %Y')})",
    xy=(row_max["datetime"], pm25_max),
    xytext=(0, 10),
    textcoords="offset points",
    ha="center"
)

plt.annotate(
    f"Terendah ({row_min['station']} – {row_min['datetime'].strftime('%b %Y')})",
    xy=(row_min["datetime"], pm25_min),
    xytext=(0, -15),
    textcoords="offset points",
    ha="center"
)

plt.legend(title="Stasiun Pemantauan", bbox_to_anchor=(1.05, 1), loc="upper left")
plt.tight_layout()
plt.show()

"""### Pertanyaan 2: Sejauh mana perbedaan konsentrasi PM2.5 antar stasiun pemantauan selama periode pengamatan 2013–2017?"""

plt.figure(figsize=(14, 6))

sns.lineplot(
    data=annual_pm25,
    x="datetime",
    y="PM2.5",
    hue="station",
    marker="o"
)

plt.title("Perbandingan Rata-rata Tahunan PM2.5 Antar Stasiun (2013–2017)")
plt.xlabel("Tahun Pengamatan")
plt.ylabel("Rata-rata PM2.5 (µg/m³)")

axis = plt.gca()
axis.xaxis.set_major_locator(mdates.YearLocator())
axis.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
plt.xticks(rotation=0)

pm25_high = annual_pm25["PM2.5"].max()
pm25_low = annual_pm25["PM2.5"].min()

plt.axhline(pm25_high, linestyle=":", linewidth=1.2, label=f"Tertinggi: {pm25_high:.2f}")
plt.axhline(pm25_low, linestyle=":", linewidth=1.2, label=f"Terendah: {pm25_low:.2f}")

peak_row = annual_pm25.loc[annual_pm25["PM2.5"].idxmax()]
low_row = annual_pm25.loc[annual_pm25["PM2.5"].idxmin()]

plt.annotate(
    f"Puncak ({peak_row['station']}, {peak_row['datetime'].year})",
    xy=(peak_row["datetime"], pm25_high),
    xytext=(5, 10),
    textcoords="offset points"
)

plt.annotate(
    f"Terendah ({low_row['station']}, {low_row['datetime'].year})",
    xy=(low_row["datetime"], pm25_low),
    xytext=(5, -15),
    textcoords="offset points"
)

plt.legend(title="Stasiun Pemantauan", bbox_to_anchor=(1.05, 1), loc="upper left")
plt.tight_layout()
plt.show()

air_quality_df["weekday_num"] = air_quality_df["datetime"].dt.weekday

air_quality_df["day_category"] = np.where(
    air_quality_df["weekday_num"] < 5,
    "Hari Kerja",
    "Akhir Pekan"
)

avg_pm25_daytype = (
    air_quality_df
        .groupby(["station", "day_category"])["PM2.5"]
        .mean()
        .reset_index()
)

pivot_pm25 = avg_pm25_daytype.pivot(
    index="station",
    columns="day_category",
    values="PM2.5"
)

labels = pivot_pm25.index
x_pos = np.arange(len(labels))
bar_width = 0.4

plt.figure(figsize=(12, 5))
plt.bar(x_pos - bar_width/2, pivot_pm25["Hari Kerja"], bar_width, label="Hari Kerja")
plt.bar(x_pos + bar_width/2, pivot_pm25["Akhir Pekan"], bar_width, label="Akhir Pekan")

plt.title("Rata-rata PM2.5: Hari Kerja vs Akhir Pekan per Stasiun")
plt.xlabel("Stasiun Pemantauan")
plt.ylabel("Rata-rata PM2.5 (µg/m³)")
plt.xticks(x_pos, labels, rotation=45)
plt.legend()
plt.tight_layout()
plt.show()

air_quality_df["weekday_name"] = air_quality_df["datetime"].dt.day_name()

weekday_order = [
    "Monday", "Tuesday", "Wednesday",
    "Thursday", "Friday", "Saturday", "Sunday"
]

avg_pm25_weekday = (
    air_quality_df
        .groupby(["station", "weekday_name"])["PM2.5"]
        .mean()
        .reset_index()
)

plt.figure(figsize=(10, 5))

for st in avg_pm25_weekday["station"].unique():
    subset = avg_pm25_weekday[avg_pm25_weekday["station"] == st]
    subset = subset.set_index("weekday_name").reindex(weekday_order)

    plt.plot(
        weekday_order,
        subset["PM2.5"],
        marker="o",
        label=st
    )

plt.title("Pola Rata-rata PM2.5 Berdasarkan Hari dalam Minggu")
plt.xlabel("Hari")
plt.ylabel("Rata-rata PM2.5 (µg/m³)")
plt.xticks(rotation=45)
plt.legend(title="Stasiun Pemantauan", bbox_to_anchor=(1.05, 1), loc="upper left")
plt.tight_layout()
plt.show()

"""**Insight:**

Hasil visualisasi menunjukkan bahwa seluruh stasiun pemantauan memiliki pola fluktuasi konsentrasi PM2.5 yang relatif serupa dari waktu ke waktu.
Selain itu, terlihat adanya pola musiman, di mana konsentrasi PM2.5 cenderung lebih tinggi pada musim dingin dan lebih rendah pada musim panas.

Analisis berbasis hari dalam minggu menunjukkan bahwa konsentrasi PM2.5 mengalami peningkatan secara bertahap dari awal hari kerja menuju akhir pekan.
Pada sebagian besar stasiun, nilai rata-rata PM2.5 pada akhir pekan tercatat sedikit lebih tinggi dibandingkan hari kerja, dengan puncak konsentrasi umumnya terjadi pada hari Sabtu.

Stasiun dengan tingkat polusi yang relatif tinggi secara konsisten menunjukkan kenaikan konsentrasi yang lebih tajam menjelang akhir pekan.
Sementara itu, stasiun dengan tingkat PM2.5 yang lebih rendah tetap mengikuti pola yang sama, meskipun berada pada level konsentrasi yang lebih rendah.

## Analisis Lanjutan (Opsional)
"""



"""## Conclusion

- Conclusion

Analisis konsentrasi PM2.5 selama periode 2013–2017 menunjukkan pola fluktuatif yang dipengaruhi oleh faktor musiman. Konsentrasi PM2.5 cenderung meningkat pada akhir tahun dan menurun pada pertengahan tahun, yang mengindikasikan adanya pengaruh kondisi musiman terhadap kualitas udara. Pola ini terlihat konsisten di seluruh stasiun pemantauan, meskipun tingkat konsentrasinya berbeda-beda.

Perbandingan antar stasiun menunjukkan bahwa meskipun pola pergerakan PM2.5 relatif serupa, terdapat perbedaan tingkat konsentrasi yang cukup jelas. Beberapa stasiun secara konsisten mencatat konsentrasi PM2.5 yang lebih tinggi, sementara stasiun lainnya berada pada level yang lebih rendah. Hal ini mengindikasikan bahwa faktor lokasi dan karakteristik lingkungan sekitar stasiun memiliki peran penting dalam menentukan tingkat pencemaran udara.

Selain itu, analisis berbasis hari dalam minggu menunjukkan kecenderungan peningkatan konsentrasi PM2.5 menjelang akhir pekan, dengan nilai tertinggi umumnya terjadi pada hari Sabtu. Temuan ini mengindikasikan adanya pengaruh aktivitas manusia terhadap peningkatan polusi udara. Secara umum, kualitas udara selama periode pengamatan relatif stabil, namun tetap rentan terhadap kejadian polusi ekstrem yang bersifat temporer dan dipengaruhi oleh faktor musiman, tanpa menunjukkan indikasi perbaikan jangka panjang yang signifikan.
"""

